// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbpL1nYq97Z0zPpiZTdz2QaoaLwwbNvI',
    appId: '1:561601266702:web:f5703e93a78488e340a85f',
    messagingSenderId: '561601266702',
    projectId: 'anti-theft-ginnie',
    authDomain: 'anti-theft-ginnie.firebaseapp.com',
    storageBucket: 'anti-theft-ginnie.appspot.com',
    measurementId: 'G-N9H9512HYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVNY76wmK22Ob8PtGfnt3X_tQxXNOVHXw',
    appId: '1:561601266702:android:82a8a4886418229d40a85f',
    messagingSenderId: '561601266702',
    projectId: 'anti-theft-ginnie',
    storageBucket: 'anti-theft-ginnie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhtNHtem2-mhDcuVicsXdW-pWuUEd7co',
    appId: '1:561601266702:ios:7a6ace8708fe2ef740a85f',
    messagingSenderId: '561601266702',
    projectId: 'anti-theft-ginnie',
    storageBucket: 'anti-theft-ginnie.appspot.com',
    iosBundleId: 'com.ginnie.dont.touch.phone.antitheft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAhtNHtem2-mhDcuVicsXdW-pWuUEd7co',
    appId: '1:561601266702:ios:467887f3353359f340a85f',
    messagingSenderId: '561601266702',
    projectId: 'anti-theft-ginnie',
    storageBucket: 'anti-theft-ginnie.appspot.com',
    iosBundleId: 'com.example.antitheftalarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbpL1nYq97Z0zPpiZTdz2QaoaLwwbNvI',
    appId: '1:561601266702:web:bfb5f4e3bb36b75540a85f',
    messagingSenderId: '561601266702',
    projectId: 'anti-theft-ginnie',
    authDomain: 'anti-theft-ginnie.firebaseapp.com',
    storageBucket: 'anti-theft-ginnie.appspot.com',
    measurementId: 'G-MTSQXH5ZRH',
  );
}
